version: '3.8'
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    depends_on:
      - wordpress
    volumes:
      - "wp-data:/var/www/wordpress"
    ports:
    - "443:443"
    networks:
    - inception
  
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    networks:
      - inception
    expose:
      - "3306"
    env_file:
      - .env
    container_name: mariadb
    volumes:
      - "mariadb-data:/var/lib/mysql"


  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - "wp-data:/var/www/wordpress"
    expose:
      - "9000"
    networks:
      - inception
    env_file:
      - .env
    container_name: wordpress

networks:
  inception:
    name: inception
    driver: bridge
volumes:
  wp-data:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' 									# aucun type spécifique
      o: 'bind'
      device: '/Users/ahallali/data/wordpress'

  # - /Users/ahallali/data/wordpress
  mariadb-data:
    driver: local # ici nous stockons le volume en local
    driver_opts:
      type: 'none' 									# aucun type spécifique
      o: 'bind'
      device: '/Users/ahallali/data/mariadb'
  # - /Users/ahallali/data/mariadb